# Generated by Django 5.1.6 on 2025-03-11 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('position', models.CharField(choices=[('header', 'Sub Header'), ('between_categories', 'Între Categorii și Joburi'), ('sidebar', 'Sidebar'), ('job_listing', 'Între Listări de Joburi'), ('job_detail', 'Sub Detalii Job'), ('footer', 'Footer'), ('user_dashboard', 'Dashboard Utilizator'), ('company_dashboard', 'Dashboard Companie'), ('after_apply', 'După Aplicare')], max_length=50, verbose_name='Poziție')),
                ('ad_code', models.TextField(help_text='Cod snippet Google AdSense', verbose_name='Cod reclamă')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('display_order', models.IntegerField(default=0, verbose_name='Ordine afișare')),
                ('target_devices', models.CharField(choices=[('all', 'Toate Dispozitivele'), ('desktop', 'Desktop'), ('tablet', 'Tabletă'), ('mobile', 'Mobil')], default='all', max_length=20, verbose_name='Dispozitive țintă')),
            ],
            options={
                'verbose_name': 'Amplasare Reclamă',
                'verbose_name_plural': 'Amplasări Reclame',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Clasa CSS pentru iconiță', max_length=50, verbose_name='Iconiță CSS')),
                ('job_count', models.PositiveIntegerField(default=0, verbose_name='Număr joburi')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorii',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume companie')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anul înființării')),
                ('employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Număr angajați')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Este promovată')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Companie',
                'verbose_name_plural': 'Companii',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Oraș')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='Județ')),
            ],
            options={
                'verbose_name': 'Locație',
                'verbose_name_plural': 'Locații',
                'ordering': ['city', 'county'],
                'unique_together': {('city', 'county')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporar')], max_length=20, verbose_name='Tip job')),
                ('experience', models.CharField(choices=[('entry', 'Entry level'), ('mid', 'Mid level'), ('senior', 'Senior level'), ('executive', 'Executive level')], default='entry', max_length=20, verbose_name='Experiență')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('requirements', models.TextField(verbose_name='Cerințe')),
                ('responsibilities', models.TextField(verbose_name='Responsabilități')),
                ('benefits', models.TextField(blank=True, verbose_name='Beneficii')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salariu minim')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salariu maxim')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Este promovat')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Remote')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('filled', 'Ocupat'), ('expired', 'Expirat')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data expirării')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.location')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Joburi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profesie')),
                ('bio', models.TextField(blank=True, verbose_name='Biografie')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresă')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilizator',
                'verbose_name_plural': 'Profiluri Utilizatori',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='CV')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Scrisoare de intenție')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('reviewed', 'Verificat'), ('interviewed', 'Intervievat'), ('hired', 'Angajat'), ('rejected', 'Respins')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Aplicare',
                'verbose_name_plural': 'Aplicări',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'user')},
            },
        ),
    ]
